#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	kitty --working-directory ~ &

elif [[ "$1" == "--ff" ]]; then
	firefox &

elif [[ "$1" == "--fm" ]]; then
	thunar ~ &

elif [[ "$1" == "--obs" ]]; then
	obsidian &

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--sl" ]]; then
	slack &

elif [[ "$1" == "--pow" ]]; then
	xfce4-power-manager-settings &

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu
fi
